import rsa
import stdio
import sys


# Entry point.
def main():
    # Accept private-key n (int) and d (int) as command-line arguments.
    n = int(sys.argv[1])
    d = int(sys.argv[2])

    # Set width to the number of bits needed to encode n.
    width = rsa.bitLength(n)

    # Accept message (binary string generated by encrypt.py) from standard input.
    message = stdio.readAll()

    for i in range(0, len(message) - 1, width):
        # For each binary representation of a character...
        s = message[i:i + width]

        # Set y to the decimal representation of the character.
        y = rsa.bin2dec(s)

        # Set decryptedVal to the decrypted value of y and write to standard output.
        decryptedVal = rsa.decrypt(y, n, d)
        stdio.write(chr(decryptedVal))


if __name__ == '__main__':
    main()